SECRET_KEY         = "sk_test"
WALLET_ADDRESS     = 'sent...'
SERVER_ADDRESS     = "https://your-server.de:1000"
API_ENDPOINT       = "/api/endpoint"
MAX_SPEND_ENDPOINT = "/api/endpoint2"
USERNAME           = 'username'
PASSWORD           = 'password'
CCOMPAREAPI        = 'ccapi'
CCOMPARE_API_URL   = "https://min-api.cryptocompare.com/data/price?fsym=DVPN&tsyms=USD&extraParams=Meile"