SECRET_KEY         = "sk_live_"
WALLET_ADDRESS     = 'sent'
SERVER_ADDRESS     = "https://your-server.de:1000"
API_ENDPOINT       = "/endpoint"
MAX_SPEND_ENDPOINT = "/endpoint"
USERNAME           = 'username'
PASSWORD           = 'password'
CCOMPAREAPI        = 'ccapi'
CCOMPARE_API_URL   = "https://min-api.cryptocompare.com/data/price?fsym=DVPN&tsyms=USD&extraParams=Meile"