#
# WARNING   WARNING     WARNING     WARNING     WARNING     WARNING     WARNING     WARNING
#
# Travis-ci doesn't supports python runs on windows platform right now (2019.09.09). This medium story
# https://medium.com/@dirk.avery/travis-ci-python-and-windows-2f9a1b6dd096 can didn't helped either.
# (wexpect is a compicated case)
#
# So travis build paused! See appveyor builds. (https://ci.appveyor.com/project/raczben/wexpect)

language: python
dist: xenial   # required for Python >= 3.7
matrix:
  include:
    - stage: test
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install virtualenv
        - ls -la /c/Python37/Scripts
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
      # command to install dependencies
      install:
        - pip install .[test]
      # command to run tests
      script:
        - tox
      # Push the results back to codecov
      after_success:
      - codecov

notifications:
  email:
    on_success: never
    on_failure: always
    